package com.ticketpro.vendors.dpt.PaystationInfoService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 11/8/2015 8:10:24 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
public class WS_Enums {

    public enum SoapProtocolVersion{
        	Default(0),
        	Soap11(1),
        	Soap12(2);
        
        private int code;
        
        SoapProtocolVersion(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static SoapProtocolVersion fromString(String str)
        {
            if (str.equals("Default"))
                return Default;
            if (str.equals("Soap11"))
                return Soap11;
            if (str.equals("Soap12"))
                return Soap12;
            return null;
        }
    }
    public enum VersionType{
        	v10(0),
        	v11(1);
        
        private int code;
        
        VersionType(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static VersionType fromString(String str)
        {
            if (str.equals("v10"))
                return v10;
            if (str.equals("v11"))
                return v11;
            return null;
        }
    }
    public enum ByEventType{
        	All(0),
        	Battery(1),
        	BillAcceptor(2),
        	BillStacker(3),
        	CardReader(4),
        	CoinAcceptor(5),
        	CoinChanger(6),
        	CoinHopper(7),
        	Paystation(8),
        	Printer(9),
        	CoinCanister(10),
        	CoinEscrow(11);
        
        private int code;
        
        ByEventType(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static ByEventType fromString(String str)
        {
            if (str.equals("All"))
                return All;
            if (str.equals("Battery"))
                return Battery;
            if (str.equals("BillAcceptor"))
                return BillAcceptor;
            if (str.equals("BillStacker"))
                return BillStacker;
            if (str.equals("CardReader"))
                return CardReader;
            if (str.equals("CoinAcceptor"))
                return CoinAcceptor;
            if (str.equals("CoinChanger"))
                return CoinChanger;
            if (str.equals("CoinHopper"))
                return CoinHopper;
            if (str.equals("Paystation"))
                return Paystation;
            if (str.equals("Printer"))
                return Printer;
            if (str.equals("CoinCanister"))
                return CoinCanister;
            if (str.equals("CoinEscrow"))
                return CoinEscrow;
            return null;
        }
    }
}
